### ISSUE TITLE
Not working, help

### ISSUE THREAD

**Issue by Cidolf** [Black-Hell-Team/LordPhish#11]
I already have ngrok authentication but I still get errors like this:

 [~] Select an option: 2

[01] Ngrok
[02] Localhost Run
[03] Localhost

[*] Choose a Port Forwarding option: 1
[*] Starting php server...
lord.sh: line 979: cd: webpages/verzion: No such file or directory
[*] Starting ngrok server...
[*] Send this link to the Target:

[*] Or using tinyurl: Error

[*] Waiting victim open the link ctrl + c to exit...

![Screenshot 2024-06-04 214714](https://github.com/Black-Hell-Team/LordPhish/assets/160384231/e213d1db-7658-4ee5-927e-31e0640ff611)

Help

**Comment by sukalaper** [comment]
> I already have ngrok authentication but I still get errors like this:
> 
> [~] Select an option: 2
> 
> [01] Ngrok [02] Localhost Run [03] Localhost
> 
> [_] Choose a Port Forwarding option: 1 [_] Starting php server... lord.sh: line 979: cd: webpages/verzion: No such file or directory [_] Starting ngrok server... [_] Send this link to the Target:
> 
> [*] Or using tinyurl: Error
> 
> [*] Waiting victim open the link ctrl + c to exit...
> 
> ![Screenshot 2024-06-04 214714](https://private-user-images.githubusercontent.com/160384231/336475824-e213d1db-7658-4ee5-927e-31e0640ff611.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NzQxMDksIm5iZiI6MTcxODQ3MzgwOSwicGF0aCI6Ii8xNjAzODQyMzEvMzM2NDc1ODI0LWUyMTNkMWRiLTc2NTgtNGVlNS05MjdlLTMxZTA2NDBmZjYxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQxNzUwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWNmYmVmMDk0NjAzNTY4ZDMxYThhM2U4YTk4ZmFkZjE3NTNkYzI4ZmY1Y2NkOTVkYTEzYzkxOWU2OWExNzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-eIgyOgw5Mz7e3N3FvGtCAa3q4BefE6PBW86AyUuEjk)
> 
> Help

That's because the environment variable at `02:Facebook` is not set, you can check the code at line 194.
