### ISSUE TITLE
No Links Generated!! 

### ISSUE THREAD

**Issue by metalpandit** [Black-Hell-Team/LordPhish#3]
Greetings for your tool 👍

I'm using NGrok server to host the page, but it's not generating any links for the victim nor it's generating any tinyurl links brother! 
I'm on termux!! And I've installed everything as mentioned !
Help !

**Comment by Ch4r0nN** [comment]
> Greetings for your tool 👍
> 
> I'm using NGrok server to host the page, but it's not generating any links for the victim nor it's generating any tinyurl links brother! 
> I'm on termux!! And I've installed everything as mentioned !
> Help !
> 

Have you authenticated ngrok?
