### ISSUE TITLE
Please help it isn't working

### ISSUE THREAD

**Issue by justinruck080** [Black-Hell-Team/LordPhish#5]
[01] Ngrok
[02] Localhost Run
[03] Localhost

[*] Choose a Port Forwarding option: 1
[*] Starting php server...
[*] Starting ngrok server...
[*] Send this link to the Target:

[*] Or using tinyurl: Error

[*] Waiting victim open the link ctrl + c to exit...

[*] IP Found!
grep: webpages/steam/ip.txt: No such file or directory
grep: webpages/steam/ip.txt: No such file or directory
[*] Victim IP:
[*] User-Agent:
[*] Saved: steam/saved.ip.txt
cat: webpages/steam/ip.txt: No such file or directory

[*] Waiting credentials ...

**Comment by Ch4r0nN** [comment]
You need autenticate ngrok.
