### ISSUE TITLE
Links Not generated throu ngrok

### ISSUE THREAD

**Issue by shdfgj** [Black-Hell-Team/LordPhish#9]
Hello! I have done all that u have mentioned, firstly when i select ngrok it says send this link to victim: but its all blank in next line 
it says or using tinyurl: Error, PLEASE HELP

**Comment by kingpsycopr** [comment]
Same with me

**Comment by Ch4r0nN** [comment]
> Hello! I have done all that u have mentioned, firstly when i select ngrok it says send this link to victim: but its all blank in next line 
> it says or using tinyurl: Error, PLEASE HELP

Did you make the ngrok account? To use ngrok you need to create an account on the ngrok website and authenticate your ngrok account through the terminal...
